---
title: "ej_screen"
format: html
warning: false
error: false
---

```{r}
library(tidyverse)
library(sf)
library(here)
library(stars)
library(tmap)


# read in geodatabase of EJScreen data at the Census Block Group level
ejscreen <- sf::st_read(here::here("data", "ejscreen","EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb")) 

# filter to a state you are interested in
california <- ejscreen %>%
  dplyr::filter(ST_ABBREV == "CA") 

# filter to a county you are interested in
la <- ejscreen %>%
  dplyr::filter(CNTY_NAME %in% c("Los Angeles County"))

sf <- ejscreen %>%
  dplyr::filter(CNTY_NAME %in% c("San Francisco County"))

riv <- ejscreen %>%
  dplyr::filter(CNTY_NAME %in% c("Riverside County"))

ie <- ejscreen %>%
  dplyr::filter(CNTY_NAME %in% c("Riverside County", "San Bernardino County"))
# find the average values for all variables within counties
california_counties <- aggregate(california, by = list(california$CNTY_NAME), FUN = mean)
```

```{r}
tmap_mode("plot")
```

```{r}
tm_shape(la) +
  tm_graticules() +
  tm_polygons(fill = "PEOPCOLORPCT", fill.legend = tm_legend(title = "People of Color (%)")) +
  tm_scalebar() +
  tm_compass(position = c("right", "bottom"))
```

```{r}
tm_shape(la) +
  tm_polygons(fill = "DSLPM", fill.legend = tm_legend(title = "Diesel Particulate Matter")) +
  tm_scalebar() +
  tm_compass(position = c("right", "bottom"))
```

```{r}
tm_shape(sf) +
  tm_polygons(fill = "LOWINCPCT", fill.legend = tm_legend(title = "Percent of Low Income Households", orientation = "portrait")) +
  tm_scalebar() +
  tm_compass(position = c("right", "bottom"))

```

```{r}
tm_shape(sf) +
  tm_graticules() +
  tm_polygons(fill = "PEOPCOLORPCT", fill.legend = tm_legend(title = "People of Color (%)")) +
  tm_scalebar() +
  tm_compass(position = c("right", "bottom"))
```

```{r}
tm_shape(ie) +
  tm_graticules() +
  tm_polygons(fill = "PEOPCOLORPCT", 
              fill.legend = tm_legend(title = "Low Income \nHouseholds", 
                                      orientation = "portrait", 
                                      tm_pos_out = c("center", "right"),
                                      frame = FALSE,
                                      width = 3.75),
              fill.scale = tm_scale_continuous(values = "-magma", 
                                               labels = c("0%", "20%", "40%", 
                                                          "60%", "80%", "100%"))) +
  tm_scalebar(position = tm_pos_in("right", "top")) +
  tm_compass(position = c("left", "top")) +
  tm_title("Distribution of Low Income Households in Riverside County")

```

```{r}
tm_shape(ie) +
  tm_graticules() +
  tm_polygons(fill = "LIFEEXPPCT", 
              fill.legend = tm_legend(title = "Percent of Homes \nwith Lead Paint", 
                                      tm_pos_out = c("center", "bottom"),
                                      orientation = "portrait",
                                      frame = FALSE), 
              fill.scale = tm_scale_continuous(values = "-magma", 
                                               labels = c("0%", "20%", "40%", 
                                                          "60%", "80%", "100%"))) +
  tm_scalebar(position = tm_pos_in("right", "top")) +
  tm_compass(position = c("left", "top")) +
  tm_title("Distribution of Homes with Lead Paint in Riverside County")
  
```


```{r}
tm_shape(ie) +
  tm_graticules() +
  tm_polygons(fill = "PRE1960PCT", 
              fill.legend = tm_legend(title = "Percent of Homes with Lead Paint", 
                                      tm_pos_out = c("center", "bottom"),
                                      orientation = "landscape"), 
              fill.scale = tm_scale_continuous(values = "-magma", 
                                               labels = c("0%", "20%", "40%", 
                                                          "60%", "80%", "100%"))) +
  tm_compass(position = c("right", "top")) +
  tm_scalebar(position = tm_pos_in("right", "bottom")) +
  tm_title("Distribution of Homes with Lead Paint in the Inland Empire")
```



